global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'llm'
    metrics_path: '/metrics/'
    static_configs:
      - targets: ['llm-services:8000']
    scrape_interval: 10s
    scrape_timeout: 5s
  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
  